services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:18-alpine
    ports:
      - "15432:5432"
    env_file:
      - .env
    
